twitter: "https://twitter.com/nerdycap007"
github: "https://github.com/amansharma007"
instagram: "https://instagram.com/nerdycap007"
youtube: "https://www.youtube.com/channel/UCZqsCkhACnMBFupfPWpJQGQ"
medium: "https://medium.com/@nerdycap007"