baseURL = "https://nerdycap.com/"
languageCode = "en-us"
title = "The NerdyCap Blog | Excerpts from the life of a dreamer..."

# Novela settings
theme = "hugo-theme-novela"

paginate = 6

[taxonomies]
author = "authors"
