baseURL = "https://nerdycap.com/"
languageCode = "en-us"
title = "The NerdyCap Blog | Vue.js | JavaScript | HTML | CSS"

# Novela settings
theme = "hugo-theme-novela"

paginate = 6

[taxonomies]
author = "authors"
