baseURL = "https://nerdycap.com/"
languageCode = "en-us"
title = "The NerdyCap Blog | Excerpts from the life of a coder/dreamer..."

# Novela settings
theme = "hugo-theme-novela"

paginate = 6

[permalinks]
post = '/:filename/'

[taxonomies]
author = "authors"
